### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by fthamura** [hadyrashwan/concerto-docker-build#1]
will you create installatoin guide

and what the .R for?

**Comment by hadyrashwan** [comment]
it is a quick and dirty  automated build just following this https://github.com/campsych/concerto-platform/wiki/Linux-installation if you have docker installed just do
`git clone https://github.com/hadyrashwan/concerto-docker-build.git` 
` cd concerto-docker-build/`
`sudo docker build -f DOCKERFILE  -t concerto . `
`sudo docker run -d -p 80:80 concerto `
the R file is for installing the R dependencies for concerto-platform  . an official docker build is on its way based https://github.com/campsych/concerto-platform/issues/89 so I just did this repo just to try new concerto releases, with some more refactor it can be used for scalability.

I can write an installation guide by tomorrow.

**Comment by hadyrashwan** [comment]
the guide is  added its basically the  commands I gave to  you
