### ISSUE TITLE
docker image in dockerhub

### ISSUE THREAD

**Issue by fthamura** [hadyrashwan/concerto-docker-build#2]
do you have your own docker image regarding concerto

so we just run it ;)

**Comment by hadyrashwan** [comment]
yes but I thought of not putting it on docker hub to avoid confusion when the official one is available

**Comment by fthamura** [comment]
I dont think it is same

use hadyrashwan/concerto  that mean yours :)

but yes if you fork :) 

but this project name is concerto-docker-build

**Comment by hadyrashwan** [comment]
here you go
` sudo docker run -d -it -p 80:80  hadyrashwan/concerto `
