### ISSUE TITLE
21.71

### ISSUE THREAD

**Issue by fthamura** [hadyrashwan/concerto-docker-build#3]
we find bugs , several test doesnt run in the 21.8

any idea to make the 21.71 in docker?

**Comment by hadyrashwan** [comment]
I found a problem in my docker image , Im building it right now so just try it first like next 3 hours I will put it on dockerhub
in regards to 21.71 I don't know which commit  represent which  version it seems like concerto-platfrom isn't using tags I opened an issue for this

**Comment by hadyrashwan** [comment]
I added a docker image tagged with 2.186 try it  , while we are waiting for the reply from concerto developers

**Comment by fthamura** [comment]
any idea to run step by step about this release, may be in the future, I can become your release manager here also :)

**Comment by hadyrashwan** [comment]
if you checked my issue on concerto , no release tagging is available .Nothing can be done about that

**Comment by hadyrashwan** [comment]
https://github.com/campsych/concerto-platform/issues/98

**Comment by hadyrashwan** [comment]
@fthamura  I did add 2.171 , I also updated the dockerfile to take commit hash and mysql password as parameters .
