### ISSUE TITLE
step by step make it from source

### ISSUE THREAD

**Issue by fthamura** [hadyrashwan/concerto-docker-build#4]
Hi Hady

Can share the steps to make like your docker image, but from concerto source?

I think to create R script and upload, in volume 

any idea?

**Comment by hadyrashwan** [comment]
I download the concerto latest code and run through the setup.
my image is made of the following :
deb script which download PHP apache and mysql
R script which installs R packages that are needed 
concerto build which follows the guide from concerto on how to setup the system 
concerto run which just keeps the server running

**Comment by fthamura** [comment]
which line that the .sh get the source from dev concertp platform

right now i just test run r and fetch by the question to get result..

**Comment by hadyrashwan** [comment]
`git clone https://github.com/campsych/concerto-platform.git
` in concerto_setup.sh the 7th line

**Comment by fthamura** [comment]
thx
